version: '3.4'
services:
  ### database ###
  database:
    container_name: smore-database
    image: postgres:${POSTGRES_VERSION}
    environment:
      - POSTGRES_PASSWORD
    networks:
      - smore
    ports: 
      - '${POSTGRES_PORT}:5432'
    volumes:
      - database:/var/lib/postgresql/data

  ### application ###
  web:
    container_name: smore-web
    build:
      context: ./docker
      args:
        - WEB_PHP_VERSION
    image: smore/web
    environment:
      - WEB_ENTRYPOINT
      - WEB_HTTPS_PORT
    networks:
      - smore
    ports:
      - '${WEB_HTTP_PORT:-80}:80'
      - '${WEB_HTTPS_PORT:-443}:443'
    volumes:
      - ./docker/conf/vhost.conf:/etc/apache2/sites-available/000-default.conf
      - ./docker/conf/vhost-ssl.conf:/etc/apache2/sites-available/default-ssl.conf
      - ./docker/logs/apache:/var/log/apache2
      - ./docker/logs/symfony:/var/www/var/log
      - ./docker/scripts:/scripts
      - ./smore:/var/www
      - symfony-cache:/var/www/var/cache
    depends_on:
      - database

networks:
  smore:
    driver: bridge

volumes:
  database:
    driver: local
  symfony-cache:
    driver: local
